# 
FROM python:3.11-slim

WORKDIR /app



COPY requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r /app/requirements.txt

COPY . .

EXPOSE 4004

ENV GRADIO_ANALYTICS_ENABLED="False"
ENV PYTHONPATH=/app

CMD ["python", "app.py"]