# syntax=docker/dockerfile:1.4

FROM --platform=$BUILDPLATFORM golang:1.24.10-alpine AS builder

ARG TARGETOS
ARG TARGETARCH

WORKDIR /app

RUN apk add --no-cache git

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN GOOS=$TARGETOS GOARCH=$TARGETARCH go build -o server . && chmod +x server

FROM --platform=$TARGETPLATFORM alpine:latest

WORKDIR /app

RUN apk --no-cache add ca-certificates

COPY --from=builder /app/server .

EXPOSE 4001

CMD ["./server"]